class WelcomeController < ApplicationController
    # this file was generated by running the command 
    # rails g controller welcome

    # Inside of a controller, every method is called an "action"
    def index
        # by default rails will render templete within view
        # under views/welcome (it will match the controller name)
        # this acction will render out the file views/welcome/index.html.erb
    end

    def goodbye
    end

    def form_example
    end

end
